# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
# create an array of 10 zeros
np.zeros(10)

# create an array of 10 ones
np.ones(10)

# create an array of 10 fives
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [5]:
# convert list to numpy array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# select elements from the array
a[2] # select the 3rd element

# replace elements in the array
a[2] = 10

In [6]:
# create a range of numbers
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
# create an array of numbers with a step
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Multi-dimensional arrays

In [9]:
# create a matrix 5x2
m =  np.zeros((5, 2))

In [12]:
# specify you want to get a column
m[:, 1] = np.ones(5)

m[:, 1]

array([1., 1., 1., 1., 1.])

## Randomly generates arrays

In [15]:
np.random.seed(2) # seed for reproducibility
np.random.rand(5, 2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
# generate random integers
np.random.randint(0, 10, (5,2))

array([[4, 5],
       [7, 3],
       [6, 4],
       [3, 7],
       [6, 1]])